#version: '3.8' (deprecated)

services:
  polestar2mqtt:
    build: .
    container_name: "polestar2mqtt"
    restart: always
    environment:
      TZ:                "Europe/Berlin"
      POLESTAR_EMAIL:    "xx@xxx"
      POLESTAR_PASSWORD: "XXX"
      POLESTAR_VIN:      "LPSVSEDEEMLxxxxxx"
      POLESTAR_CYCLE:    300 # Sekunden
      MQTT_BROKER:       "192.168.1.100"
      MQTT_PORT:         "1883"
      MQTT_USER:         "" # muss leer bleiben, wenn kein Login beim Broker erforderlich
      MQTT_PASSWORD:     "" # s.o.
      BASE_TOPIC:        "polestar2"

# ***** EOF *****
