#
# Docker: CONSULitAS/Polestar_2_MQTT_Docker
#
# (C) CONSULitAS, Dr. Jochen Groppe, 2024 - GPL V3
#
# https://github.com/CONSULitAS/Polestar_2_MQTT_Docker/tree/main
#
# Docker Container with gateway between Polestar API and MQTT
#
# Get it up and running:
# - install docker
# - download and rename this file to 'docker-compose.yml' (remove '_example')
# - create a '.env' file for your Polestar credentials and MQTT login if needed
# - edit values under 'environment:' to match your needs
# - optionally customize local-files/graphql_queries.py based on the sample file
# - no additional network needed
# - start container with 'docker compose up'

#version: '3.8' (deprecated)

services:
  polestar2mqtt:
    # build: . # only used for local build
    image: consulitas/polestar_2_mqtt_docker:latest
    container_name: "polestar2mqtt"
    restart: always
    environment:
      TZ:                "Europe/Berlin"
      POLESTAR_EMAIL:    "${POLESTAR_EMAIL}"
      POLESTAR_PASSWORD: "${POLESTAR_PASSWORD}"
      POLESTAR_VIN:      "${POLESTAR_VIN}"
      POLESTAR_CYCLE:    270 # seconds
      MQTT_BROKER:       "192.168.1.100" # IP or DNS name
      MQTT_PORT:         "1883"
      MQTT_USER:         "${MQTT_USER}" # keep empty in .env if broker has no login
      MQTT_PASSWORD:     "${MQTT_PASSWORD}" # keep empty in .env if broker has no password
      MQTT_BASE_TOPIC:   "polestar2"

      # optional SoC forwarding to OpenWB v1 (e.g. if no NodeRed installation is available)
      #OPENWB_HOST:     "openwb.lan or ip address of OpenWB"
      #OPENWB_PUBLISH:  True
      #OPENWB_PORT:     1883 # default 1883 if unset
      #OPENWB_LP_NUM:   1 # optional: defaults to 1, change for other LP
    volumes:
      - ./local-files:/local-files
    labels:
      # automatic update using Watchtower (https://github.com/containrrr/watchtower) highly recommended
      - "com.centurylinklabs.watchtower.enable=true"

    logging:
      driver: "json-file"
      options:
        max-size: "1m"  # maximum log size 1 MiB
        max-file: "3"   # keep only 3 logfiles

# ***** EOF *****
