#
# Docker: CONSULitAS/Polestar_2_MQTT_Docker
#
# (C) CONSULitAS, Dr. Jochen Groppe, 2024 - GPL V3
#
# https://github.com/CONSULitAS/Polestar_2_MQTT_Docker/tree/main
#
# Docker Container with gateway between Polestar API and MQTT
#
# Get it up and running:
# - install docker
# - download and rename this file to 'docker-compose.yml' (remove '_example')
# - edit values under 'environment:' to match your needs
# - no volumes or network needed
# - start container with 'docker compose up'

#version: '3.8' (deprecated)

services:
  polestar2mqtt:
    # build: . # only used for local build
    image: consulitas/polestar_2_mqtt_docker:latest
    container_name: "polestar2mqtt"
    restart: always
    environment:
      TZ:                "Europe/Berlin"
      POLESTAR_EMAIL:    "xx@xxx"
      POLESTAR_PASSWORD: "XXX"
      POLESTAR_VIN:      "LPSVSEDEEMLxxxxxx" # no spaces allowed
      POLESTAR_CYCLE:    270 # seconds
      MQTT_BROKER:       "192.168.1.100" # IP or DNS name
      MQTT_PORT:         "1883"
      MQTT_USER:         "" # has to be empty ("") if broker has no password
      MQTT_PASSWORD:     "" # has to be empty ("") if broker has no password
      BASE_TOPIC:        "polestar2"

      # optional SoC forwarding to OpenWB v1 (e.g. if no NodeRed installation is available)
      #OPENWB_HOST:     "openwb.lan or ip address of OpenWB"
      #OPENWB_PUBLISH:  True
      #OPENWB_PORT:     1883 # default 1883 if unset
      #OPENWB_LP_NUM:   1 # optional: defaults to 1, change for other LP

    labels:
      # automatic update using Watchtower (https://github.com/containrrr/watchtower) highly recommended
      - "com.centurylinklabs.watchtower.enable=true"

# ***** EOF *****
